name: schematics
version: 1.0.0-dev.1.6
homepage: https://github.com/CoderNamedHendrick/schematics
repository: https://github.com/CoderNamedHendrick/schematics
issue_tracker: https://github.com/CoderNamedHendrick/schematics/issues
topics:
  - schematics
  - diagrams
  - drawing
  - maps
  - floor-plan

description: 'Draw 2d schematics diagrams'

screenshots:
  - description: 'schematic diagram on mobile'
    path: screenshots/mobile_sc1.png

  - description: 'schematic diagram on mobile 2'
    path: screenshots/mobile_sc2.png

  - description: 'schematic diagram on desktop'
    path: screenshots/desktop_sc1.png

  - description: 'schematic diagram on desktop 2'
    path: screenshots/desktop_sc2.png


environment:
  sdk: ^3.1.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: